name: 🐛 Bug Report
description: File a bug report to help us improve the module
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and examples
          required: true
        - label: I am using a supported version of Terraform
          required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of the terraform-latitudesh-server-module are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: "1.5.7"
    validations:
      required: true

  - type: input
    id: provider-version
    attributes:
      label: Latitude.sh Provider Version
      description: What version of the Latitude.sh provider are you using?
      placeholder: "2.5.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you running Terraform on?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the server to be created with the specified configuration..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, the following error occurred..."
    validations:
      required: true

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration
      description: Please provide your Terraform configuration (remove sensitive data)
      render: hcl
      placeholder: |
        module "server" {
          source = "git::https://github.com/latitudesh/terraform-latitudesh-server-module.git"
          
          hostname         = "my-server"
          operating_system = "ubuntu_24_04_x64_lts"
          plan             = "c2-small-x86"
          project          = "proj_xxxxxxxxxxxxx"
          site             = "SAO"
        }
    validations:
      required: true

  - type: textarea
    id: terraform-output
    attributes:
      label: Terraform Output
      description: Please provide the relevant Terraform output/error messages
      render: shell
      placeholder: |
        $ terraform apply
        Error: ...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Create a new Terraform configuration with...
        2. Run `terraform init`
        3. Run `terraform apply`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This might be related to..."

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have ideas on how to fix this, please share them
      placeholder: "This could potentially be fixed by..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue for your project?
      options:
        - Low - Nice to have
        - Medium - Blocks some functionality
        - High - Blocks critical functionality
        - Critical - Completely unusable
    validations:
      required: true
