name: Scheduled Tests

on:
  schedule:
    # Run every Monday at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

env:
  TF_VERSION: "1.12.0"

  TFLINT_VERSION: latest

jobs:
  full-validation:
    name: Full Module Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact

      - name: Generate test SSH keys
        run: |
          # Create test SSH keys for CI
          mkdir -p ~/.ssh/
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N "" -C "ci-test-key"
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          echo "Generated test SSH key for CI"
          ls -la ~/.ssh/

      - name: Test All Examples
        run: |
          for example in examples/*/; do
            echo "Testing $example"
            cd "$example"
            terraform init -backend=false
            terraform plan
            cd - > /dev/null
          done
        env:
          TF_VAR_latitude_auth_token: "fake-token-for-plan"

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Scheduled validation failed',
              body: `
                The scheduled validation workflow failed.
                
                **Workflow:** ${context.workflow}
                **Run ID:** ${context.runId}
                **Date:** ${new Date().toISOString()}
                
                Please check the workflow logs for details.
              `,
              labels: ['bug', 'ci/cd']
            });
